= Database Configuration on Linux
:toc: right
:page-aliases: configuration/database/index.adoc, configuration/database/db_conversion.adoc
:description: ownCloud requires a database in which administrative data is stored. 

:avoid-deadlocks-galery-haproxy-url: https://severalnines.com/blog/avoiding-deadlocks-galera-set-haproxy-single-node-writes-and-multi-node-reads
:haproxy-url: https://www.haproxy.org/
:maxscale-url: https://github.com/mariadb-corporation/MaxScale/wiki
:maxscale-readwrite-splitting-with-galera-cluster-url: https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale-14/maxscale-readwrite-splitting-with-galera-cluster/
:mysql-set-transaction-url: https://dev.mysql.com/doc/refman/5.7/en/set-transaction.html
:mariadb-binary-log-overview-url: https://mariadb.com/kb/en/mariadb/overview-of-the-binary-log/
:mysql-binary-log-overview-url: https://dev.mysql.com/doc/refman/5.6/en/binary-log.html
:mariadb-docs-url: https://mariadb.com/kb/en/
:mysql-docs-url: https://dev.mysql.com/doc/
:postgresql-docs-url: https://www.postgresql.org/docs/manuals/

== Introduction

{description} The following databases are currently supported:

* xref:mysql-mariadb[MySQL / MariaDB]
* xref:postgresql[PostgreSQL]

NOTE: MySQL or MariaDB databases are the recommended database engines.

== Requirements

Choosing to use MySQL / MariaDB or PostgreSQL as your database requires, that you install and set up the server software first.  

The steps for configuring a third party database are beyond the scope of this document. Please refer to the documentation below, for your database vendor.

* The {mariadb-docs-url}[MariaDB Knowledge Base]
* The {mysql-docs-url}[MySQL documentation]
* The {postgresql-docs-url}[PostgreSQL documentation]

=== MySQL / MariaDB

==== Enabling Binary Logging 

ownCloud is currently using a `TRANSACTION_READ_COMMITTED` transaction isolation to avoid data loss under high load scenarios (e.g., by using the sync client with many clients/users and many parallel operations). This requires a disabled or correctly configured binary logging when using MySQL or MariaDB. Your system is affected if you see the following in your log file during the installation or update of ownCloud:

[source,plaintext]
----
An unhandled exception has been thrown: exception `PDOException' with message `SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.'
----

There are two solutions:

* One is to disable binary logging. Binary logging records all changes to your database, and how long each change took. The purpose of binary logging is to enable replication and to support backup operations.

* The other is to change the BINLOG_FORMAT = STATEMENT in your database configuration file, or possibly in your database startup script, to BINLOG_FORMAT = MIXED or BINLOG_FORMAT = ROW. See {mariadb-binary-log-overview-url}[Overview of the Binary Log] and {mysql-binary-log-overview-url}[The Binary Log] for detailed information.

==== Set `READ COMMITTED` as the Transaction Isolation Level

As discussed above, ownCloud is using the `TRANSACTION_READ_COMMITTED` transaction isolation level. Some database configurations are enforcing other transaction isolation levels. To avoid data loss under high load scenarios (e.g., by using the sync client with many clients/users and many parallel operations), you need to configure the transaction isolation level accordingly. Please refer to the {mysql-set-transaction-url}[MySQL manual] for detailed information.

==== Configuring the Storage Engine

Since ownCloud 7, only InnoDB is supported as a storage engine. Some shared hosts do not support InnoDB and only MyISAM. Running ownCloud in such an environment is not supported.

== Parameters

For setting up ownCloud to use any database, use the instructions in xref:installation/installing_with_docker.adoc[Installing With Docker].
You should not have to edit the respective values in the ownCloud config. However, in exceptional cases, for example, if you want to connect your ownCloud instance to a database created by a previous installation of ownCloud, some modification might be required.

=== MySQL / MariaDB

MariaDB is backward compatible with MySQL. All instructions work for both, so you will not need to replace or revise any existing MySQL client commands.

////
The PHP configuration in `/etc/php/<php-version>/apache2/conf.d/20-pdo_mysql.ini` could look like this:

[source,ini]
----
; configuration for php mysql module
; priority=20
extension=pdo_mysql.so

[mysql]
mysql.allow_local_infile=On
mysql.allow_persistent=On
mysql.cache_size=2000
mysql.max_persistent=-1
mysql.max_links=-1
mysql.default_port=
mysql.default_socket=/var/lib/mysql/mysql.sock  # Debian squeeze: /var/run/mysqld/mysqld.sock
mysql.default_host=
mysql.default_user=
mysql.default_password=
mysql.connect_timeout=60
mysql.trace_mode=Off
----
////

An ownCloud instance configured with MySQL would contain the hostname on which the database is running, a valid username and password to access it, and the name of the database. The config as created by the xref:installation/installing_with_docker.adoc[Installing with Docker] procedure will therefore contain entries such as:

[source,php]
----
<?php

"dbtype"        => "mysql",
"dbname"        => "owncloud",
"dbuser"        => "username",
"dbpassword"    => "password",
"dbhost"        => "localhost",
"dbtableprefix" => "oc_",
----

==== Configure MySQL for 4-byte Unicode Support

For supporting such features as emoji, both MySQL (or MariaDB) *and* ownCloud need to be capable of using 4-byte Unicode instead of the default 3-byte and configured accordingly.

[NOTE]
====
If you are setting up

* a new ownCloud installation, using version 10.0 or above, *and* 
* you’re using a _minimum_ MySQL version of 5.7

*then you don’t need to do anything*, as support is checked during setup and used if available. 
====

However, if

* you have an *existing* ownCloud installation that you need to convert to use 4-byte Unicode support +
*or*
* you are working with a MySQL version _earlier_ than version 5.7

then you need to do two things:

. In your MySQL configuration, add the configuration settings below.
If you already have them configured, update them to reflect the values specified:
+
[source,mysql]
----
[mysqld]
innodb_large_prefix=ON
innodb_file_format=Barracuda
innodb_file_per_table=ON
----

. Run the following occ command:
+
--
[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} db:convert-mysql-charset
----

When this is done, tables will be created with:

* A `utf8mb4` character set.
* A `utf8mb4_bin` collation.
* `row_format` set to compressed.
--

[TIP]
====
For more information, please either refer to xref:configuration/server/config_sample_php_parameters.adoc[config.sample.php], or have a read through the following links:

* https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix
* https://mariadb.com/kb/en/library/innodb-system-variables/#innodb_large_prefix
* http://www.tocker.ca/benchmarking-innodb-page-compression-performance.html
* http://dev.mysql.com/doc/refman/5.7/en/charset-unicode-utf8mb4.html
* https://dev.mysql.com/doc/refman/5.7/en/innodb-file-format.html
* https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix
====

=== PostgreSQL

////
If you decide to use a PostgreSQL database, make sure that you have installed and enabled the {php-net-url}/manual/en/book.pgsql.php[PostgreSQL extension] and the
{php-net-url}/manual/en/ref.pdo-pgsql.php[PostgreSQL PDO extension] in PHP. The PHP configuration in `/etc/php/<php-version>/apache2/conf.d/20-pdo_pgsql.ini`
could look like this:

[source,bash]
----
; configuration for php pgsql module
; priority=20
extension=pdo_pgsql.so

[PostgresSQL]
pgsql.allow_persistent = On
pgsql.auto_reset_persistent = Off
pgsql.max_persistent = -1
pgsql.max_links = -1
pgsql.ignore_notice = 0
pgsql.log_notice = 0
----

[TIP]
====
The default configuration for PostgreSQL (at least in Ubuntu 14.04) is to use the peer authentication method. Check `/etc/postgresql/9.3/main/pg_hba.conf` to find out which authentication method is used in your setup.
====

To start the PostgreSQL command-line mode use:

[source,bash]
----
sudo -u postgres psql -d template1
----

Then a `template1=\#` prompt will appear. You can now enter your commands as required. When finished, you can quit the prompt by entering:

[source,psql]
----
\q
----
////

An ownCloud instance configured with PostgreSQL will contain the hostname on which the database is running, a valid username and password to access it, and the name of the database. The config as created by xref:installation/installing_with_docker.adoc[Installing With Docker] would contain entries like this:

[source,php]
----
<?php

"dbtype"        => "pgsql",
"dbname"        => "owncloud",
"dbuser"        => "username",
"dbpassword"    => "password",
"dbhost"        => "localhost",
"dbtableprefix" => "oc_",
----

== Troubleshooting

=== How to Workaround General Error: 2006 MySQL Server Has Gone Away

The database request takes too long, and therefore the MySQL server times out. It's also possible that the server is dropping a packet that is too large. Please refer to the manual of your database for how to raise the configuration options `wait_timeout` and/or `max_allowed_packet`.

Some shared hosts are not allowing access to these config options. For such systems, ownCloud is providing a `dbdriveroptions` configuration option within your `config/config.php` where you can pass such options to the database driver. Please refer to the xref:configuration/server/config_sample_php_parameters.adoc[sample PHP configuration parameters] for an example.

=== Useful SQL Commands

==== Show Database Users

[options="header",cols="2"]
|===
|MySQL
|PostgreSQL

|`SELECT User,Host FROM mysql.user;`
|`SELECT * FROM pg_user;`
|===

==== Show Available Databases

[options="header",cols="2"]
|===
|MySQL
|PostgreSQL

|`SHOW DATABASES;`
|`\l`
|===

==== Show ownCloud Tables in Database

[options="header",cols="2"]
|===
|MySQL
|PostgreSQL

|`USE owncloud; SHOW TABLES;`
|`\c owncloud; \d`
|===

==== Quit Database

[options="header",cols="2"]
|===
|MySQL
|PostgreSQL

|`quit;`
|`\q`
|===

=== How to Solve Deadlock Errors

[source,plaintext]
----
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
----

==== Explanation

This error occurs when two transactions write and commit to the same rows in separate cluster nodes. Only one of them can successfully commit. The failing one will be aborted. For cluster level aborts, Galera Cluster returns a deadlock error. 

==== Solution

The solution, for Galera Cluster, would be to send all write requests to a single DB node, instead of all of them. Here is {avoid-deadlocks-galery-haproxy-url}[a useful guide], when using {haproxy-url}[HAProxy]. 

The same concept applies when {maxscale-url}[MaxScale] is used as a DB proxy. It needs to be configured to send all write requests to a single DB node instead all of them and balance read statements across the rest of the nodes. Here is {maxscale-readwrite-splitting-with-galera-cluster-url}[a useful guide] on how to configure MaxScale with Read/Write splitting.

==== Enabling Causality Checks

Additionally, to solve this issue, when using Galera Cluster, customers should try to set `wsrep_sync_wait=1`. When enabled, the node triggers causality checks in response to certain types of queries. This is disabled by default.
