site:
  title: ownCloud Server Documentation
  url: https://doc.owncloud.com
  start_page: server::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD
  # the docs-xxx git is just present for the test build to satisfy used references
  # the real build is made in the docs repo using correct values
  #- url: https://github.com/owncloud/docs-main.git
  #  branches:
  #  - master
  - url: https://github.com/owncloud/docs-webui.git
    branches:
    - master

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   global attributes loaded via antora extension
#   server
    # note that the version attributes just need to be present and have next as key
    # as they are just here for the test build
    latest-server-version: 'next@'   # do not change, soft set, correctly defined via antora.yml
    previous-server-version: 'next@' # do not change, soft set, correctly defined via antora.yml
    latest-server-download-version: 'next@' # do not change, soft set, correctly defined via antora.yml
    current-server-version: 'next@'         # do not change, soft set, correctly defined via antora.yml
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki

antora:
  extensions:
    - ./ext-antora/generate-index.js
    #- ./ext-antora/comp-version.js
    - require: ./ext-antora/load-global-site-attributes.js
      attributefile: https://raw.githubusercontent.com/owncloud/docs/refs/heads/master/global-attributes.yml
      #attributefile: ./global-attributes.yml
      enabled: true
    - require: ./ext-antora/find-orphaned-files.js
      #printavailable: true
      #excludeextension: ['.png', '.gif']
      #falsepositives: ./false-positives.txt
      pathfilter: ['modules/owncloud_web', 'modules/classic_ui']
      excludecomponents: ['webui']
      stopafterfind: true
      enabled: false
    # for testing only, prints attributes used
    # use only one or the other, output can be big
    #- ./ext-antora/attributes-used-in-site-yml.js
    #- ./ext-antora/attributes-used-in-antora-yml.js

# note that when we do pdf generation with Antora assembler, we need to add the attribute:
# format: 'pdf' to the build process (to be checked if needed also in the docs repo)
