site:
  title: ownCloud Server Documentation
  url: https://doc.owncloud.com
  start_page: server::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD
  # the docs git is just present for the test build to satisfy used references
  # the real build is made in the docs repo using correct values
  - url: https://github.com/owncloud/docs.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-webui.git
    branches:
    - master

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   build relevant
    idprefix: ''
    idseparator: '-'
    experimental: ''
    # the page-component-build-list is used in docs-ui
    page-component-build-list: 'docs, server, ocis, user, desktop, ios-app, android'
#   common
    docs-base-url: 'https://doc.owncloud.com'
    oc-complete-base-url: 'https://download.owncloud.com/server/stable'
    oc-contact-url: 'https://owncloud.com/contact/'
    oc-help-url: 'https://owncloud.com/docs-guides/'
    oc-marketplace-url: 'https://marketplace.owncloud.com'
    oc-central-url: 'https://central.owncloud.org'
    oc-support-url: 'https://owncloud.com/support'
#   docs
    latest-docs-version: 'next'
    previous-docs-version: 'next'
#   server
    latest-server-version: '10.10'
    latest-server-download-version: '10.10.0'
    previous-server-version: '10.9'
    current-server-version: '10.10'
    oc-changelog-url: 'https://owncloud.com/changelog/server/'
    oc-install-package-url: 'https://software.opensuse.org/download.html?project=isv%3AownCloud%3Aserver%3A10&package=owncloud-complete-files'
    oc-examples-server-url: 'https://owncloud.install.com/owncloud'
    oc-examples-server-ip: '127.0.0.1'
    oc-examples-username: 'username'
    oc-examples-password: 'password'
    oc-complete-name: 'owncloud-complete-latest'
    occ-command-example-prefix: 'sudo -u www-data php occ'
    occ-command-example-prefix-no-sudo: 'php occ'
    php-net-url: 'https://www.php.net'
    php-supported-versions-url: 'https://www.php.net/supported-versions.php'
    http-status-codes-base-url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Status'
    std-port-http: '8080'
    std-port-memcache: '11211'
    std-port-mysql: '3306'
    std-port-redis: '6379'
#   webui
    latest-webui-version: 'next'
    previous-webui-version: 'next'
#   ocis
    latest-ocis-version: 'next'
    previous-ocis-version: 'next'
    ocis-version: 'next'
    ocis-downloadpage-url: 'https://download.owncloud.com/ocis/ocis/testing/'
    ocis-ext-includes: 'https://raw.githubusercontent.com/owncloud/ocis/docs/extensions/_includes/'
#   desktop
    latest-desktop-version: 'next'
    previous-desktop-version: 'next'
#   ios-app
    latest-ios-version: 'next'
    previous-ios-version: 'next'
#   android
    latest-android-version: 'next'
    previous-android-version: 'next'
#   branded
    latest-branded-version: 'next'
    previous-branded-version: 'next'
  extensions:
    - ./lib/extensions/tabs.js
    - ./lib/extensions/remote-include-processor.js
    - ./node_modules/asciidoctor-kroki/src/asciidoctor-kroki.js

