= Database Upgrade
:toc: right
:upgrade-mariadb-url: https://mariadb.com/kb/en/upgrading/
:compressed-row-format-url: https://mariadb.com/kb/en/innodb-compressed-row-format/#read-only

== Introduction

Usually, when upgrading a database, follow the guides the vendor provides.

This document supports an upgrade in case there are prerequisites and/or special steps to be taken to upgrade to a particular database version.

== Upgrading to MariaDB 10.6+

ownCloud runs fine when using a MariaDB version lower than 10.6. You can upgrade ownCloud as usual without special considerations regarding the database.

When planning to upgrade to MariaDB 10.6+, some prerequisites have to be met and upgrade steps have to be taken. 

This is mostly due to the fact that, unlike before, in MariaDB 10.6 _tables of the COMPRESSED row format are read-only by default_. For more information see the {compressed-row-format-url}[InnoDB COMPRESSED Row Format] document.

NOTE: This process only needs to be carried out once.

=== Overview

. You must have upgraded your ownCloud installation to version 10.9 or above. To do so, follow the xref:maintenance/upgrading/manual_upgrade.adoc[Manual ownCloud Upgrade] guide.

. Backup your ownCloud installation, especially the database to rollback in case of issues. To do so, follow the xref:maintenance/backup_and_restore/backup.adoc[Backing up ownCloud] guide.

. Prepare the database for the upgrade with an xref:configuration/server/occ_command.adoc#restore-the-table-format[occ command].

. Follow the respective {upgrade-mariadb-url}[Upgrading MariaDB] guide to upgrade MariaDB.

=== Detailed Upgrade Steps

. If not already done, upgrade the xref:maintenance/upgrading/manual_upgrade.adoc[ownCloud installation] to version 10.9 or above.

. Set ownCloud in maintenance mode
+
[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} maintenance:mode --on
----

. Prevent browser access: +
Configure your web proxy server to prevent users from accessing ownCloud via the web.

. Run an occ command to prepare the database for the upgrade
+
[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} db:restore-default-row-format
----

. Upgrade MariaDB to version 10.6+
+
--
Follow the instructions in the respective {upgrade-mariadb-url}[Upgrading MariaDB] guide to upgrade MariaDB. +
If required, run the `mysql_upgrade` command when using a compose setup including MySQL.

[source,bash]
----
docker compose exec owncloud mysql_upgrade -uroot -p
----
--

. Set ownCloud back to normal operation mode:
+
[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} maintenance:mode --off
----

. Enable browser access +
Configure your web proxy server to enable users to access ownCloud via the web.

