= Manually Move the Data Directory
:toc: right
:page-aliases: maintenance/manually-moving-data-folders.adoc
:description: Follow these instructions if you need to migrate the data directory to a Dockerized installation.

:mysql-string-replace-function-url: http://www.mysqltutorial.org/mysql-string-replace-function.aspx
:mariadb-docker-url: https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/installing-and-using-mariadb-via-docker

== Introduction

{description}

Migrating the data directory, where ownCloud hosts user data, is a critical migration.

Different steps need to be taken when migrating from an existing installation to a Dockerised one in the following scenarios using ownCloud Classic 11. *In both cases, updating the database is required*:

. Local, no NFS: +
Copy the `data` directory to a new location.

. The `data` directory is part of an existing NFS export: +
The old export can be removed and a new export with only the `data` directory needs to be provided and mounted.

This guide assumes that:

* The data directory of a local installation is: +
`/var/www/owncloud/data`

* The Docker volume data directory is: +
`<mount-point>/files`

* The internal data directory of a Dockerized installation is: +
`/mnt/data/files`

* The ownCloud's database name is: +
`owncloud`

Please change the paths above to reflect your environment.

== Overview of Steps

The following steps are necessary to migrate the data directory.

. Stop access via the web (proxy) server
. Enable maintenance mode
. Sync / remount your Data directory
. Adjust ownCloud's configuration
. Check permissions
. Disable maintenance mode
. Start the web proxy server

Look at each section below for a detailed description.

== Preparation

=== Prevent User Access via the Web (Proxy) Server

To prevent any active user connections to your ownCloud instance, stop access to it via the web (proxy) server. Refer to the web (proxy) server description to find out how to do this.

=== Enable Maintenance Mode

It is necessary to enable maintenance mode to avoid running cron jobs. To enable maintenance mode, run the following command.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} maintenance:mode --on
----

=== Database

Back up your database by making a copy or an export. This way, you can always revert if something goes horribly wrong.

== Data Directory

Depending on the Setup, the `data` directory either needs to be copied or remounted.

For small instances with limited data, copying is probably the best option. For anything with more user data, such as an existing NFS mount, remounting to a different location is preferable. If you have more user data that you are currently hosting locally, now might be a good time to switch to NFS.

=== Sync to a new Location

Please note that the target mount point is used intentionally as the Docker volume mount point for ease of handling. In this example, the source and target are on the same server and the source path is the ownCloud's default. Adapt accordingly to suit your needs.

[source,bash]
----
sudo rsync -avz /var/www/owncloud/data <mount_point>/files
----

=== Mounting with NFS

If the data directory is already part of a NFS mount point such as `/mnt/owncloud/data`, unmount it, remove the export, create a new export including the data directory and mount it to `<mount_point>/files`.

IMPORTANT: Only mount the data directory from the source and not the full owncloud directory including the data directory.

== Adjust ownCloud Database Configuration

{mariadb-docker-url}#connecting-to-mariadb-from-outside-the-container[Connect to your database, window=_blank] and enter the following command to select the ownCloud database: Adapt the database name if it is not named as shown:

[source,sql]
----
use owncloud;
----

=== Update the oc_storages Table

First print all the affected paths to be changed:

[source,sql]
----
select * from oc_storages where id like 'local::%';
----

Then update the database paths and adapt them accordingly:

[source,sql]
----
BEGIN TRANSACTION;

UPDATE oc_storages
  SET id = REPLACE(id, '/var/www/owncloud/data', '/mnt/data/files')
WHERE id LIKE 'local::%'`;

# check with the select statement above
# in case something went wrong
# ROLLBACK;

# otherwise use
# COMMIT;

----

=== Update the oc_accounts Table

You next need to update the `home` column in the `oc_accounts` table.
This column contains the absolute path for user folders, e.g., `/mnt/owncloud/data/my_user`.

If a user does not have the path already set, you have to identify the users `id` and set the path with the following command, user by user.
This example assumes the user name is `my_user` and their id is `1`. Note that id's are incremental, meaning the account you created first will have id `1` and so on.

Run the SQL below:

[source,sql]
----
UPDATE oc_accounts SET home='/mnt/owncloud/data/my_user'
  WHERE id=1;
----

For all users who already have a path like `/var/www/owncloud/data/` in your database, you can use the `REPLACE` command:

[source,sql]
----
UPDATE oc_accounts 
  SET home = REPLACE(
    home,
    '/var/www/owncloud/data/',
    '/mnt/owncloud/data/'
  );
----

For more information follow the complete MySQL {mysql-string-replace-function-url}[REPLACE] command syntax.

CAUTION: Please don’t copy and paste this example verbatim — nor any of the others. They are examples only.

=== Update the oc_jobs table

The next area to check is the `oc_jobs` table. 
The logrotate process may have hard-coded a non-standard (or old) value for the data path. 
To check it, run the SQL below and see if any results are returned:

[source,sql]
----
SELECT * FROM oc_jobs
  WHERE class = 'OC\Log\Rotate';
----

If results are returned, run the SQL below to update them, changing the id value as appropriate.

[source,sql]
----
UPDATE oc_jobs 
  SET argument = REPLACE(
    argument,
    '\\/var\\/www\\/owncloud\\/data\\/',
    '\\/mnt\\/owncloud/data\\/'
  )
  WHERE id = <id of the incorrect record>;
----

CAUTION: The old data path will be written with `\/`.
Therefore you must add one, additional, backslash, like this: `\\/`.

== Fix the config.php Settings

To fix the config.php settings:

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} config:system:set --value /mnt/owncloud/data datadirectory
----

=== Adjust config.php

. Change the `datadirectory` key in your `config.php` to the new path.
  To do so, start an editor of your choice and open `/var/www/owncloud/config/config.php`

. Change the value of the key from `'datadirectory' => '/var/www/owncloud/data',` to `'datadirectory' => '/mnt/owncloud/data',`.

== Disable Maintenance Mode

To disable maintenance mode of your instance run the following command:

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} maintenance:mode --off
----

== Start the Web Proxy Server

Follow the web proxies server description for how to enable access to teh ownCloud instance.

== Scan the Files

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} files:scan --all
----
