= Migrating to Kiteworks Private Content Network
:toc: right
// :toclevels: 1
:description: Kiteworks offers a great software stack keeping your shared data completely fenced, secured and monitored. It offers additional features ownCloud does not provide. This guide describes how to migrate an ownCloud instance to a https://www.kiteworks.com[Kiteworks Private Content Network (PCN)].

== Introduction

{description}

See the image below to get an overview about the building blocks of both sides.

{empty} +

image::maintenance/kiteworks-migration.drawio.svg[Migrate to Kiteworks Overview, width=500]

== Overview

The migration works with an app and a small binary to be installed on the ownCloud side. The app and the binary are provided by ownCloud as part of the guided migration. Get in touch with {oc-support-url}[ownCloud support] to get them. Both sides need to be fully configured and running, have a defined minimum release installed and are reachable for each other. If release requirements are not satisfied, you MUST upgrade first.

The migration process is made in the following steps which are:

* Prepare the environment.
* Verify upcoming migration steps.
* Run the migration.

NOTE: If it is planned to integrate LDAP into Kiteworks, ownCloud highly recommends to have the Kiteworks PCN connected and configured to an LDAP server upfront to avoid double user entries that will naturally exist when connecting to an LDAP server after the migration has been done.

=== Migrated Items

The following items will get migrated. In case, special rules apply and are noted:

* Ordinary users.
* The content of the users home directory.
* User shares recieved. +
As long they reference content from another users home.
* User shares granted. +
As long they reference content from the users home.
* Share permissions. +
Will be translated into Kiteworks predefined roles.

=== Items Excluded from the Migration

The following items are NOT migrated. These items need to be migrated manually:

* External mounts like +
`WND`, `SMB`, `Google Drive`, etc. +
This includes admin mounts and user created mounts. See the xref:#owncloud[ownCloud prerequisites] section for a special note. 
* S3 primary object store cannot be migrated for the time being.
+
--
IMPORTANT: If you have configured S3 primary as your storage locataion for the users home, get in touch with {oc-support-url}[ownCloud support].
--
* Federated shares.
* Public links.
* Guest Users.

== Limitations

* While ownCloud fully respects letter casing for file and folder names, Kitworks does not distinguish casings. In case, there is a casing conflict file or directory created that a user can rename according his needs.

* When group shares have been defined, groups will not get created in Kiteworks. Instead, each member of the group will get an individual user share to the object shared.

* Users have been able on the ownCloud side to login using either the display name, the login name or the email address. Kiteworks only allows to login via the email address. The presence of the users email address in ownCloud is a mandatory requirement.

== Prerequisites

To be prepared for the migration, both sides need to match the prerequisites. Please read this section carefully.

=== ownCloud

* As a major prerequisite, the ownCloud instance *must* be running on release 10.14 or higher. If this requirement is not matched, migration can not be started as the necessary app checks the minimum version.

* Shell access is necessary. +
`occ` commmands need to be started and `rclone` needs to be granted executable.

* Install both, from ownCloud provided migration components which are:
** the migration app
** the custom rclone binary 

// install rclone from github.com/oks-maytech/rclone/tree/kiteworks-backend
//install app from github.com/owncloud/migrate_to_kiteworks

* All users must have email-addresses and they must be unique. +
The migration verify step will point out missing email addresses. These must be recitified before any migration can start.

=== Kiteworks

* As a major prerequisite, the Kiteworks instance *must* be running on the "Vanice" release or higher. If this requirement is not matched, migration can not be started.

* You need to login in the Kiteworks appliance as system admin.

* If it is planned to use LDAP or Active Directory for user authentication and group management, ownCloud *highly* recommends to configure this *before* the migration is started. If such a integration is started after the migration has been made, you will most likely have to deal with double present user entries. 

