= Migrating to Kiteworks Private Content Network
:toc: right
// :toclevels: 1
:description: Kiteworks offers a great software stack keeping your shared data completely fenced, secured and monitored. It offers additional features ownCloud does not provide. This guide describes how to migrate an ownCloud instance to a Kiteworks Private Content Network (PCN).

== Introduction

{description}

See the image below to get an overview about the building blocks of both sides.

{empty} +

image::maintenance/kiteworks-migration.drawio.svg[Migrate to Kiteworks Overview, width=500]

== Overview

The migration works with an app and a small binary to be installed on the ownCloud side. The app and the binary are provided by ownCloud as part of the guided migration. Both sides need to be fully configured and running, have a defined minimum release installed and are reachable for each other. If release requirements are not satisfied, you MUST ugrade first.

NOTE: ownCloud highly recommends to have the Kiteworks PCN connected and configured to an LDAP server upfront to avoid double user entries that will natuarally exist when connecting to an LDAP server after the migration has been done.

=== Migrated Items

The following items will get migrated. In case, special rules apply and are noted.

=== Items Excluded from the Migration

The following items are NOT migrated. These items need to be migrated manually.

== Limitations

* While ownCloud fully respects latter casing for file and folder names, Kitworks does not distinguish casings. In case, there is a casing conflict file or directory created that a user can rename accordingly his needs.

== Prerequisites


=== ownCloud


=== Kiteworks
