= Introduction

Welcome to the ownCloud Classic Administration Guide. This guide describes administration tasks for ownCloud, the flexible open source file synchronization and sharing solution.

== Installation Changes

IMPORTANT: Unlike previous releases, ownCloud Classic 11 is only available as a Docker image containing the necessary libraries, such as PHP 8.

== Target Audience

This guide is for administrators who want to install, administer, and optimize their ownCloud servers. To learn more about the ownCloud Web user interface, and desktop and mobile clients, please refer to their respective manuals. See the xref:developer_manual:index.adoc[developer manual] if you would like to contribute.

== Editions

ownCloud server is available in three editions:

* The free community-supported server. This is the core server for all editions.
* The Standard Subscription for customers who want paid support for the core Server, without Enterprise applications.
* The Enterprise Subscription provides paid support for the Enterprise Edition. This includes the core Server and Enterprise apps.
