= Scripts for the Script-Guided Installation
:toc: right
:toclevels: 1
:apache_docs: https://httpd.apache.org/docs/2.4/
:description: The purpose of the provided scripts is to ease installation or upgrades of ownCloud instances. Using these scripts, you can also reapply ownership and access rights on linked directories if needed.

== Introduction

{description}

== General Info

It is important to understand how these scripts work and why things are done to process all the steps for a successful and smooth installation or upgrade.

Installation::
When you do a fresh installation using this set of scripts, consider using links for the `data/` and `apps-external/` directories. Any copying or moving big directories can cause issues which can be avoided by using links. When doing an upgrade after an installation, the scripts can re-link those directories but will not "migrate" standard ones. If standard directories are used, the admin has to select a suitable method to migrate those directories as part of the upgrade process. You will get notified about this task if necessary.

Migrating from standard to linked directories::
You can at any time relocate your `data/` and `apps-external/` directories and link them to the old location. This does not impact the functionality but eases upgrade steps a lot. In such a case, parametrize the instance script with the proper values to be prepared for the next upgrade. See some details at the xref:configuration[configuration section] below.

Upgrading::
When upgrading, the scripts rename the current ownCloud directory (usually `owncloud`) to `owncloud-timestamp`. A new and fresh owncloud directory will be created where the files from the tar archive get extracted to. By doing so, nothing gets deleted, overwritten or moved and the existing instance is secured to go back to in case it is needed. Note that the script does not take care of the database. You have to manage a xref:maintenance/backup_and_restore/backup.adoc#backup-the-database[database backup] yourself. When you have decided to use links for `data/` and `apps-external/`, the script will re-link these directories. Nothing gets moved. You can also (re)run the scrips on linked directories to set correct ownership and permissions. When using standard directories, you have to manually migrate them according to your environment and also manually check for correct ownership and permissions.
+
The scripts take care of your configuration. The relevant files are _copied_ from the backup.
+
If the upgrade was successful, you can delete the backup or keep it based on your requirements.

Scripts::
There are two scripts available. The instance script defines the environment for your ownCloud while the preparation script called by the instance script performs the main tasks. Note that the preparation script asks a couple of questions to decide what you want to achieve.
+
If you administrate more than one ownCloud instance, you still only need the one `owncloud_prep.sh` script. This script is doing the main job. Have as many instance scripts as you have instances to maintain. Only the instance scripts need configuration, like the respective target directory and other predefined information. The `instance.sh` script (or however you will name it) calls `owncloud_prep.sh` with the configuration you defined for the respective instance.

The scripts are written for the `bash` shell. After you copy and pasted them, save both in a location for easy access.

WARNING: Use the following scripts at your own risk. They may not work as expected if not properly configured.

NOTE: The scripts are only working with tar archives as sources for installations and upgrades.

TIP: You can also use these scripts if you want to set or reapply strong permissions on linked drectories.

== Configuration

* This is a brief overview of main directories in case you use linking. Note that `/mnt/owncloud_data` can be for example nfs mounted. The script takes care of proper linking the source to the target.
+
[source,plaintext]
----
/mnt/owncloud_data
 └ apps-external
 └ data

/var/www/owncloud
 └ apps
 └ apps-external -> /mnt/owncloud_data/apps-external
 └ data -> /mnt/owncloud_data/data
  ..
----

* This is a brief overview of main directories in case you use standard directories
+
[source,plaintext]
----
/var/www/owncloud
 └ apps
 └ apps-external
 └ data
  ..
----

While this makes no difference for an installation, upgrading is much easier as you do not need to take care of migrating directories as they are simply re-linked.

NOTE: You only need to edit the `instance.sh` script (or however you name it), if you want to change the default settings.

The following table illustrates the variables to be configured and what they mean.

[width="90%",cols="20%,80%",options="header"]
|===
|Variable | Description
|ocname   | The name of your directory containing the owncloud files (default is owncloud)
|ocroot   | The path to ocname, usually /var/www (no trailing slash, default is /var/www)
|linkroot | The path to your source directory for linking **data** and **apps-external** (default /mnt/owncloud_data). You have to prepare this directory in advance and give it proper ownership and r/w permissions for the webserver user. Note that the **apps** directory is always part of the tar archive and therefore be extracted at its default location without being linked.
|htuser   | The webserver user (default www-data)
|htgroup  | The webserver group (default www-data)
|rootuser | The root user (default root). Necessary to run some commands in the script. Note that the script is not intended to run as superuser for security reasons.
|===

. `ocname` +
This is the _directory name_ where your ownCloud files will be saved. Suggestion: Use `owncloud` for a single instance but feel free to pick any name you like. Do not use slashes (`/`).
+
NOTE: With only one site to serve, use `html` as it requires no additional settings to maintain on the Apache webserver after the installation. If you use any other name like `owncloud`, you need to set the correct directory in the Apache configuration. For more information, see the {apache_docs}[Apache documentation]. If you are hosting additional websites on the same server, better use a name different from the Apache default (html).

. `ocroot` +
This is the _path_ where `ocname` will be created, for example `/var/www`. +
The path must be resolvable! Do not use trailing slashes (`/`). +
`ocroot`/`ocname` is the  path/directory where your webserver points to (document root). +
The script resolves this for example to `/var/www/owncloud`.

. `linkroot` +
Although not mandatory, it is highly recommended that you use symbolic links for the `data` and `apps-external` directories. The `data` directory can grow very large and any copy or move process might take a long time on upgrades. Therefore this directory is often put on external drives or on NFS mounts. The `apps-external` directory is used for all apps not provided by the ownCloud installation. With any physical upgrade you perform, manual intervention like copying may be necessary before finalizing and upgrade if you are not using links. The use of symbolic links makes the administration much easier and less error-prone.
+
The script uses `linkroot` as base for both the `data` and `apps-external` directories. If not already present, it creates the directories from scratch and links them, both for the installation and on upgrades.
+
If you consider using symbolic links, create a base directory at the location of choice (for example: `/mnt/oc_data`) and let that directory be owned by your webserver's user or group. Use this directory as your `linkroot`. Do not use trailing slashes (`/`).

. `htuser` and `htgroup` +
This is the user and group the webserver uses, usually `www-data`.

. `rootuser` +
This is the name of the root user, usually `root`.

== Usage

It is mandatory to run this script with root privileges, because files and directories will be created and ownership and permissions will be set. Call the instance script like:

[source,bash]
----
sudo ./instance.sh
----

The script asks you a couple of questions which follow a logical path. Default answers are capitalized.

.When installing
the script extracts the files with tar and automatically extracts them to the target location without copying.

.In case of an upgrade
the old instance path is backed up by _renaming and adding a time stamp_. A new target folder with the old name is created. This ensures that in case of extracting and preparation issues, you can easily go back to the previous version. After a successful upgrade, you must manually remove the backup folder.

TIP: If you do not install or upgrade, the script sets ownership and permissions on linked directories only.

NOTE: In case of upgrading, if you have customized the `.htaccess` or `.user.ini` file in the ownCloud webroot, you have to manually restore any changes made after the script has finished from the backup folder. Take care to only restore the changes made but not the complete file as this file will be recreated on upgrades by the tar source and may contain different settings provided by ownCloud. Customizing `.htaccess` can be necessary when you e.g. xref:configuration/integration/ms-teams.adoc[Integrate ownCloud into Microsoft Teams].

NOTE: In case of upgrading, if you have created links to the apps-external/ and data/ directory, the script will re-link these directories. If you used standard directories, you have to manually migrate any content of these directories back after the script has run. Check that ownership and permissions are correct after migration and in doubt, let the scrips set the correct ones when using linked directories or set them manually - which can take a while depending on the size of the data/ directory. Take care not to overwrite new app versions with older ones.

=== Script Questions

* **Do you want to secure your .htaccess files post installing/upgrade (y/N)?** +
  Use this if you have configured or upgraded your instance successfully to protect
  your .htaccess files.

* **Do you want to install a new instance (y/N)?** +
  Self explaining

* **Do you want to upgrade an existing installation (y/N)?** +
  Use this if you already have a running instance. Prepare your instance by enabling
  maintenance mode. For security reasons, you will be asked before the script continues! 

* **Use links for data and apps-external directories (Y/n)?** +
  The script uses respectively checks if links or local directories will be / are used. 

* **Do you want to chmod/chown these links (y/N)?** +
  This question is only asked when you use links. If you are not installing or upgrading, 
  answering with yes, you can e.g. re-apply ownership and permissions to the linked `data` and
  `apps-external` directories. As written above, the data directory can be very large
  and may take long to complete. Note, by design, there is no progressbar... 

* **Please specify the tar file to extract with full path:** +
  Used when installing or upgrading only. Enter the full path/filename to the tar source
  file, downloaded from ownCloud.

== Final Steps

After running the script, you will see success messages when it finishes.

.When installing
Enter the URL of your ownCloud instance in a browser and continue the setup via the graphical installation wizard. For more information, see xref:installation/installation_wizard.adoc[The Installation Wizard].
The URL you need to enter in the browser depends on the webserver setup and is either an external URL or, if you installed locally, you should be able to access your ownCloud instance via a browser at `\http://127.0.0.1/owncloud/` or `\http://localhost/owncloud/`.

.When upgrading
Follow the steps printed on the screen, especially when using standard directories where you have to migrate the `data/` and `apps-external/` directories manually before finalizing the upgrade. Do not forget to reapply manually made changes made to `.htaccess` and `.user.ini` in your owncloud root directory.

.How to see the difference between two files quickly
The following example command shows you the difference between two files, which is helpful for reapplying manual changes to `.htaccess` and `.user.ini`. Change the paths, directories and files accordingly.
[source,bash]
----
diff -y -W 70 --suppress-common-lines owncloud/.user.ini owncloud_2022-02-15-09.18.48/.user.ini
----
[source,plaintext]
----
post_max_size=513M                |     post_max_size=1G
----

== Creating the scripts

Save both scripts together in a directory of your choice. Name the `instance.sh` script according to your needs, so you can easily identify to which ownCloud installation it applies. However, the script `owncloud_prep.sh` is called with exactly that name by the instance script, therefore you must save it with exactly that name.

Edit your version of the `instance.sh` script with the parameters that apply to your environment.

Next, make both scripts executable (use the correct script names instead of the placeholder):

[source,bash]
----
sudo chmod +x scriptname.sh
----

. The `instance.sh` script
+
[source,bash]
----
include::example$installation/manual_installation/instance.sh[]
----

. The `owncloud_prep.sh` script
+
[source,bash]
----
include::example$installation/manual_installation/owncloud_prep.sh[]
----
