= Server Preparation for Ubuntu 22.04
:toc: right
:toclevels: 1
:page-partial:
:ubuntu_upgrade_url: https://linuxconfig.org/how-to-upgrade-ubuntu-to-22-04-lts-jammy-jellyfish
:php-common: https://tecadmin.net/enable-disable-php-modules-ubuntu/
:ondrej-php-url: https://launchpad.net/~ondrej/+archive/ubuntu/php
:libsmbclient-php_url: https://github.com/eduardok/libsmbclient-php
:update-alternatives_url: https://manpages.ubuntu.com/manpages/focal/en/man1/update-alternatives.1.html
:phpmyadmin_latest_url: https://www.phpmyadmin.net/downloads/
:pear-package_url: https://pear.php.net/package/PEAR/
:phpseclib-url: https://phpseclib.com/docs/why

:description: This guide gives you detailed information on preparing your Ubuntu 22.04 server for the use with ownCloud.

== Introduction

{description}

The target audience for this document are experienced admins with additional needs and setup scenarios. Ubuntu 22.04 by default only provides PHP 8.1. However, PHP versions 8.0 and 8.1 are currently not supported, therefore this guide describes how to install PHP version 7.4 on Ubuntu 22.04 by the means of the {ondrej-php-url}[ondrej/php] PPA. For more information, see {php-supported-versions-url}[Currently Supported PHP Versions]. This document considers two basic scenarios. You plan to upgrade from 20.04 LTS to 22.04 LTS or you have a fresh Ubuntu 22.04 LTS installation.

IMPORTANT: PHP 8.x is currently **not** supported by ownCloud server.

IMPORTANT: Read the xref:installation/manual_installation/manual_installation_prerequisites.adoc#openssl-version[openSSL Version] notes which are important when planning to use encryption.

NOTE: The commands and links provided in this description should give you proper hints but we cannot take any responsibility.

== Upgrading from Ubuntu 20.04 to 22.04

Without going into the upgrade details, you can now upgrade directly from Ubuntu 20.04 LTS to 22.04 LTS when using the do-release-upgrade command. For more details see an example description at {ubuntu_upgrade_url}[Upgrade Ubuntu 20.04 to 22.04 LTS using command line]

[source,bash]
----
sudo apt update
----

[source,bash]
----
sudo apt upgrade
----

[source,bash]
----
sudo apt dist-upgrade
----

[source,bash]
----
sudo apt autoremove

----
[source,bash]
----
sudo apt install update-manager-core
----

[source,bash]
----
sudo do-release-upgrade
----

If you have upgraded successfully and had previously installed any versions of PHP, better uninstall all PHP versions and ALL extensions and perform a fresh PHP 7.4 native installation. To do so, stop any services which depend on or use PHP like your Web Server. Then get a list of all PHP related programs and extensions by typing:

[source,bash]
----
dpkg -l | grep php | awk '{print $2}' | tr "\n" " "
----

Disable all extensions listed (see the section
xref:useful-commands-for-managing-php-extensions[Useful Commands For Managing PHP Extensions]).

Then purge them step by step:

[source,bash]
----
sudo apt purge <package name from the list above>
----

Alternatively, if you are fine removing all packages listed, you can run:

[source,bash]
----
sudo apt purge `dpkg -l | grep php | awk '{print $2}' | tr "\n" " "`
----

NOTE: Keep a copy of your relevant `php.ini` and other configuration files as reference _before_ you start purging, to quickly reconfigure your PHP 7.4 installation afterwards.

After deinstallation of all versions and extensions of PHP and cleaning up all remnants, you should have an empty `/etc/php` directory. You can proceed like on a fresh installation of Ubuntu 22.04 LTS.

== Clean Ubuntu 22.04 Installation

After you have installed your Ubuntu 22.04 LTS server from scratch, use the following commands to first add the {ondrej-php-url}[ondrej/php] PPA and then install PHP 7.4 and all necessary extensions:

[source,bash]
----
sudo add-apt-repository ppa:ondrej/php -y
----

[source,bash]
----
sudo apt update && sudo apt upgrade
----

[source,bash]
----
sudo apt install php7.4 php7.4-intl php7.4-mysql php7.4-mbstring \
       php7.4-imagick php7.4-igbinary php7.4-gmp php7.4-bcmath \
       php7.4-curl php7.4-gd php7.4-zip php7.4-imap php7.4-ldap \
       php7.4-bz2 php7.4-ssh2 php7.4-common php7.4-json \
       php7.4-xml php7.4-dev php7.4-apcu php7.4-redis \
       libsmbclient-dev php-pear php-phpseclib
----

Note that the `php-phpseclib` package is a {phpseclib-url}[pure PHP implementation] for handling various ciphers and not dependent to the php source.

Use the following commands to install some common prerequisites:

[source,bash]
----
sudo apt install smbclient
----

[source,bash]
----
sudo apt install redis-server
----

[source,bash]
----
sudo apt install unzip
----

[source,bash]
----
sudo apt install openssl
----

[source,bash]
----
sudo apt install rsync
----

[source,bash]
----
sudo apt install imagemagick
----

== Multiple Concurrent PHP Versions

If you have multiple concurrent PHP versions installed, which will happen when using the {ondrej-php-url}[ondrej/php] PPA, you must tell your Web Server and your CLI environment which one to use. Please note that `ondrej/php` installs _ALL_ versions of PHP. To list all available versions installed and choose one of them, use the following command:

[source,bash]
----
sudo update-alternatives --config php
----

Here is an example output:

[source,plaintext]
----
There are 2 choices for the alternative php (providing /usr/bin/php).

  Selection    Path             Priority   Status
------------------------------------------------------------
* 0            /usr/bin/php7.4   74        auto mode
  1            /usr/bin/php7.4   74        manual mode
  2            /usr/bin/php8.0   80        manual mode

Press <enter> to keep the current choice[*], or type selection number:
----

You can also directly set the required PHP version:

[source,bash]
----
sudo update-alternatives --set php /usr/bin/php7.4
----

WARNING: After selecting your PHP version, it is **highly** recommended to switch to the correct compiling environment which is essential e.g. when using PECL!

[source,bash]
----
sudo update-alternatives --set phar /usr/bin/phar7.4
----

[source,bash]
----
sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.4
----

[source,bash]
----
sudo update-alternatives --set phpize /usr/bin/phpize7.4
----

[source,bash]
----
sudo update-alternatives --set php-config /usr/bin/php-config7.4
----

When using Apache PHP-FPM, you have to configure your PHP version in an Apache config file manually. In any case, the PHP version used must always be the same.

You can read more about the `update-alternatives` command in the {update-alternatives_url}[man page].

WARNING: When switching a PHP version, you **MUST** also configure the corresponding php.ini files and extensions accordingly! Extension binaries are **not** shared!

WARNING: You may get completely unexpected behaviour or a broken environment if the PHP version for the Web Server and for CLI are different!

=== Avoiding a Nasty Pitfall

If you are using a PECL install later on, check the output of the installation command soon after it has started. You will find a text like:

[source,plaintext]
----
...
PHP Api Version:         20190902
Zend Module Api No:      20190902
...
----

Then do a test by just entering the following command:

[source,bash]
----
php -i | grep extension_dir
----

If the output is different than the style below, there is a problem that needs fixing:

[source,plaintext]
----
extension_dir => /usr/lib/php/20180731 => /usr/lib/php/20180731
----

This is the output that shows a fix is needed:

[source,plaintext]
----
PHP Warning:  PHP Startup: smbclient: Unable to initialize module
Module compiled with module API=20190902
PHP    compiled with module API=20180731
These options need to match
----

As you see above, the API modules do not match and have been compiled with different versions and therefore will not work. To fix this, uninstall the PECL module with `pecl uninstall <extension_name>`, set the correct `update-alternatives` as described above and reinstall it.

== Updating pear

The following step is necessary to upgrade PEAR because of a change in PHP 7.4.1+ Note that you should always use the {pear-package_url}[latest stable PEAR release].

[source,bash]
----
pear version
----

[source,bash]
----
sudo mkdir -p /tmp/pear/cache
----

[source,bash]
----
sudo pear upgrade --force \
      --alldeps http://pear.php.net/get/PEAR-1.10.13
----

[source,bash]
----
sudo pear clear-cache
----

[source,bash]
----
sudo pear update-channels
----

[source,bash]
----
sudo pear upgrade --force
----

[source,bash]
----
sudo pear upgrade-all
----

[source,bash]
----
pear version
----

If you get any notices containing `You should add "extension=...`, check if the extension is listed in `/etc/php/7.4/mods-available`. If it is not present, add the `.ini` file manually and xref:useful-commands-for-managing-php-extensions[enable it].

Post upgrading pear, you can safely remove the directory `/tmp/pear/cache`.

See the xref:php-imagick-library[php-imagick Library] section if you are interested why an updated version of ImageMagick is necessary.

== Apache Web Server

The following command installs the Apache Web Server.

[source,bash]
----
sudo apt install libapache2-mod-php7.4 apache2
----

See the important note on using the correct xref:installation/manual_installation/manual_installation_apache.adoc#multi-processing-module-mpm[Multi-Processing Module (MPM)].

Although it's not supported by ownCloud, you can configure Apache to use `php-fpm`, the FastCGI Process Manager, which is a non-standard setup and not covered by this document.

== libsmbclient-php Library

`libsmbclient-php` is a PHP extension that uses Samba's libsmbclient library to provide Samba-related functions to PHP programs. You need to install it if you have installed `smbclient` as described above. `smbclient` is e.g. necessary if you are using the 
xref:enterprise/external_storage/windows-network-drive_configuration.adoc[Windows Network Drives app]
from ownCloud's Enterprise Edition. To install it, run the following command:

[source,bash]
----
sudo apt install php7.4-smbclient
----

When the command completes, perform the following tasks:

- Create `/etc/php/7.4/mods-available/smbclient.ini` with the following content: `extension=smbclient.so`.
- Enable the module by running `phpenmod smbclient`.
- Restart PHP and your web server by running the following command:
+
[source,bash]
----
sudo service apache2 restart
----

NOTE: Alternatively you can install `smbclient` from {libsmbclient-php_url}[source].

== php-imagick Library

When using new or extended formats for previews like HEIC or SVG, the standard installation of ImageMagick 6 lacks this functionality. You have to manually install ImageMagick 7 (while the php wrapper version should be 3.7.0, which is fine, when following the install instructions above). To do so, follow the xref:installation/manual_installation/manual_imagick7.adoc[Install an Updated ImageMagick Version] guide. See the xref:configuration/files/previews_configuration.adoc[Previews Configuration] guide how to enable preview providers for various file types.

== Useful Commands For Managing PHP Extensions

=== List Enabled PHP Extensions

If you want to retrieve a list of enabled PHP extensions run the following command:

[source,bash]
----
ls `php -i | grep "^extension_dir" | sed -e 's/.*=> //'` | sort
----

=== Enabling and Disabling PHP Extensions

To enable or disable a PHP extension for CLI, FPM or Apache, use the commands `phpenmod` or `phpdismod`.

Example:
[source,bash]
----
sudo phpenmod php-ldap
----

or

[source,bash]
----
sudo phpdismod php-ldap
----

Type the command without parameters or see this {php-common}[guide] to read more about the commands in the php-common package.

== Notes for PHP Library phpseclib

phpseclib's BigInteger uses the php-gmp (GNU Multiple Precision Arithmetic Library), php-bcmath and OpenSSL extensions, if they're available, for speed, but doesn't require them to maintain maximum compatibility. The GMP library uses an internal resource type, while the BCMath library uses strings as datatype. The most salient difference is that GMP works on _arbitrary precision integer values_ whereas BCMath allows _arbitrary precision] decimal / float-like values_.

== Database Installation

To install a database, see the
xref:installation/manual_installation/manual_installation_db.adoc[Manual Installation Databases] guide.

NOTE: Follow the procedure described in xref:useful-tips[Useful Tips] if you want to `Disable Transparent Huge Pages (THP),Transparent Huge Pages`.

You may want to use the latest version of phpmyadmin as the OS default versions lags behind the {phpmyadmin_latest_url}[latest available stable] version a lot and may report PHP errors with PHP 7.3 onwards. Follow this
xref:installation/manual_installation/upgrade_install_phpmyadmin.adoc[quick upgrade guide] to install it.

== Useful Tips

include::partial$installation/manual_installation/useful_tips.adoc[leveloffset=+1]
