= Installing & Upgrading ownCloud Enterprise Edition
:toc: right
:page-aliases: go/admin-enterprise-license.adoc

== Introduction

After you have completed your initial installation of ownCloud as detailed in the README, 
follow the instructions in xref:installation/installation_wizard.adoc[The Installation Wizard] 
to finish setting up ownCloud. To upgrade your Enterprise server, refer to 
xref:maintenance/upgrade.adoc[How to Upgrade Your ownCloud Server].

== Manual Installation

Download the ownCloud archive from your account at
https://customer.owncloud.com/owncloud, then follow the instructions at
xref:installation/manual_installation/manual_installation.adoc[Manual Installation on Linux].

=== SELinux

Linux distributions that use SELinux need to take some extra steps so
that ownCloud will operate correctly under SELinux. Please see
xref:installation/selinux_configuration.adoc[SELinux Configuration] for some recommended
configurations.

== License Keys

=== Introduction

You need to install a license key to use ownCloud Enterprise Edition.
There are two types of license keys: one is a free 30-day trial key. The
other is a full license key for Enterprise customers.

You can https://owncloud.com/download/[download and try ownCloud Enterprise for 30 days for free],
which auto-generates a free 30-day key. When this key expires your ownCloud installation is not removed, so
if you become an Enterprise customer you can enter your new key to
regain access. See https://owncloud.com/how-to-buy-owncloud/[How to Buy ownCloud]
for sales and contact information.

=== Configuration

Once you get your Enterprise license key, it needs to be copied to your
ownCloud configuration file `config/config.php` like in this example:

[source,php]
----
'license-key' => 'test-20150101-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-YYYYYY',
----

It is also possible to activate your Enterprise Edition on the webUI. Open owncloud and navigate to: 
menu:Settings[Admin > General]. Copy your license key into the field `Enter a new license:` and click `Save` to confirm.

Each running instance of ownCloud requires a license key. Keys will work
across upgrades without issue, so new keys will not be required when you
upgrade your ownCloud Enterprise to a new version.

TIP: if you want to remove the current license, open ownCloud and navigate to menu:Settings[Admin > General] and click btn:[Remove current license key].

=== User counting

Your ownCloud Enterprise License Key is valid for the purchased amount of users, as per the ownCloud EULA - ownCloud Commercial License.
When you generate a config.report you will get a counting of the enabled users, the ownCloud guest users (if the guest app is enabled) and the number of user directories created. The later is the user number you will need licenses for. Guest users are currently counted with a fair use policy - which means that you can't have more guest users then you have licensed users. If you exceed the number of licensed users please contact your account manager or ownCloud Partner and true-up as per your contract or EULA with us.
The user directories are created on first login. When a user is deleted, the user directories are deleted as well. Users which are disblaed count. The last login is irrelavant.

== Supported ownCloud Enterprise Edition Apps

See xref:installation/apps_supported.adoc[Supported Apps in ownCloud] for a list of supported apps.

NOTE: 3rd party and unsupported apps must be disabled before performing a system upgrade. Then install the upgraded versions, and after the upgrade is complete re-enable them.
