= Hardening and Security Guidance
:toc: right
:page-aliases: go/admin-security.adoc, \
go/use-https.adoc, \
go/enable-http-strict-transport-security.adoc

== Introduction

ownCloud aims to ship with secure defaults that do not need to get modified by administrators. However, in some cases some additional security hardening can be applied in scenarios were the administrator has complete control over the ownCloud instance. This page assumes that you run ownCloud Server on Apache2 in a Linux environment.

NOTE: ownCloud will warn you in the administration interface if some critical security-relevant options are missing. However, it is still up to the server administrator to review and maintain system security.

== Limit on Password Length

ownCloud uses the https://en.m.wikipedia.org/wiki/Bcrypt[bcrypt] algorithm. It only verifies the first 72 characters of passwords. This applies to all passwords you use in ownCloud: user passwords, passwords on link shares and passwords on external shares.

== Rate Limiting

Currently ownCloud deliberately does not provide any form of rate-limiting (though it does provide {oc-marketplace-url}/apps/brute_force_protection[brute-force protection]). This is because ownCloud needs to integrate in to a diverse range of environments and infrastructure, which often already provide specialized rate-limiting solutions, e.g., _Apache_, _HAProxy_, and _F5_.

If you are yet to implement a rate-limiting solution for your ownCloud instance, start by retrieving a list of all active routes. This information is obtained by running xref:configuration/server/occ_command.adoc#security[occ's security:routes command], as in the following example.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix-docker} security:routes
----

It should print a list of all the routes as in the following truncated example.

[source,plaintext]
----
+-----------------------------------------------------------+-----------------+
| Path                                                      | Methods         |
+-----------------------------------------------------------+-----------------+
| /apps/encryption/ajax/adminRecovery                       | POST            |
| /apps/encryption/ajax/changeRecoveryPassword              | POST            |
| /apps/encryption/ajax/getStatus                           | GET             |
| /apps/encryption/ajax/setEncryptHomeStorage               | POST            |
| /apps/encryption/ajax/updatePrivateKeyPassword            | POST            |
| /apps/encryption/ajax/userSetRecovery                     | POST            |
| /apps/federatedfilesharing/                               | GET             |
| /apps/federatedfilesharing/notifications                  | POST            |
+-----------------------------------------------------------+-----------------+
----

With this information, you can begin customizing a rate-limiting solution specific to your ownCloud installation.

=== Further Reading

* Rate limiting with Apache
** https://github.com/jzdziarski/mod_evasive[mod_evasive]
** https://httpd.apache.org/docs/2.4/mod/mod_ratelimit.html[mod_ratelimit]
** https://johnleach.co.uk/words/2012/05/15/rate-limiting-with-apache-and-mod-security/[mod_security]
** Rate limiting with https://www.fail2ban.org/wiki/index.php/Main_Page[Fail2Ban]
** https://centos.tips/fail2ban-behind-a-proxyload-balancer/[Fail2Ban Behind A Proxy/Load Balancer]
* https://gist.github.com/procrastinatio/6b6579230d99be5bfa26d04acd788e7a[Rate limiting with HAProxy]
* https://www.fir3net.com/Loadbalancers/F5-BIG-IP/f5-ltm-ratelimiting.html[Rate limiting with F5]

== Database

When using MySQL or MariaDB, enable the https://mariadb.com/docs/skysql-dbaas/ref/xpand/sql-modes/STRICT_TRANS_TABLES/#Setting_the_SQL_MODE[STRICT_TRANS_TABLES, window=_blank] if it is not already activated.

. Check the status of `STRICT_TRANS_TABLES`:
+
--
To check if `STRICT_TRANS_TABLES` are enabled, enter the following command: Note that the MySQL command-line client must be installed and configured. Alternatively, you can use a GUI, such as phpMyAdmin, to issue SQL commands.

[source,bash]
----
sudo mysql
----

Select the database. The example command uses `owncloud` as the database name:

[source,sql]
----
use owncloud;
----

Finally, check whether `STRICT_TRANS_TABLES` is enabled by issuing the following command:

[source,sql]
----
SELECT @@sql_mode;
----

If you see an output like this:

[source,plaintext]
----
+-------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                |
+-------------------------------------------------------------------------------------------+
| STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)
----

and it contains STRICT_TRANS_TABLES, no further action is required. Otherwise, follow the next list item to enable it.
--

. Enable `STRICT_TRANS_TABLES` for the selected database:
+
--
In the same `mysql` command line client and with the owncloud database selected, run the following command:

[source,sql]
----
SET sql_mode = CONCAT(@@sql_mode, ',STRICT_TRANS_TABLES');
----

To verify that it is enabled, enter the following command:

[source,sql]
----
SELECT @@sql_mode;
----

and check the output. 
--

== Deployment

=== Disable Preview Image Generation

ownCloud is able to generate preview images of common file types such as images or text files. By default, the preview generation for some file types that we consider secure enough for deployment is enabled. However, administrators should be aware that these previews are generated using PHP libraries written in C which might be vulnerable to attack vectors.

For high security deployments, we recommend disabling the preview generation by setting the `enable_previews` switch to `false` in `config.php`. As administrator you are also able to manage which preview providers are enabled by modifying the `enabledPreviewProviders`
option switch.

== Use HTTPS

Using ownCloud without an encrypted HTTPS connection opens up your server to a man-in-the-middle (MITM) attack and risks the interception of user data and passwords. It is a best practice, and highly recommended, to always use HTTPS on production servers and to never allow unencrypted HTTP.

Since Apache is included in the Docker image, HTTPS needs to be configured on the web proxy. Please refer to the web proxy documentation for details. You may also want to enable HTTP Strict Transport Security to prevent browsers from connecting to the ownCloud instance using HTTP and to stop site visitors from bypassing invalid certificate warnings.

Note that the free https://www.ssllabs.com/ssltest/[Qualys SSL Labs Tests] gives good guidance on whether your SSL server is correctly configured.

== Use a Dedicated Domain for ownCloud

Administrators are encouraged to install ownCloud on a dedicated domain such as `cloud.domain.tld` instead of `domain.tld` to benefit from the same-origin policy.

== Ensure that your ownCloud instance is installed in a DMZ

As ownCloud supports features such as Federated File Sharing, we do not consider Server Side Request Forgery (SSRF) a threat. Given all our external storage adapters, this can be considered a feature and not a vulnerability.

This means that a user on your ownCloud instance could probe whether other hosts are accessible from the ownCloud network. If you do not want this, you need to ensure that your ownCloud is installed in a segregated network and proper firewall rules are in place.

== Use of Security-Related Headers on the Web server

Basic security headers are provided by ownCloud already in a default environment. These include:

`X-Content-Type-Options: nosniff`::
Instructs some browsers to not sniff the MIME type of files. This is used for example to prevent browsers from interpreting text files as JavaScript.

`X-XSS-Protection: 0`::
The cross-site scripting filter is deprecated and not used in modern browsers anymore.

`X-Robots-Tag: none`::
Instructs search engines to not index these pages.

`X-Frame-Options: SAMEORIGIN`::
Prevents embedding of the ownCloud instance within an iframe on other domains to prevent clickjacking and similar attacks.

These headers are hard-coded into the ownCloud server and need no
intervention by the server administrator.

For optimal security, administrators are encouraged to let the Web server deliver these
HTTP headers. To do this, configure Apache to use the `.htaccess` file and enable the
following Apache modules:

* `mod_headers`
* `mod_env`

Verify this security change by accessing a static resource and check the above mentioned security headers are delivered.

== Use Fail2ban

Another approach to hardening ownCloud server is to use an intrusion detection system. An excellent one is https://www.fail2ban.org/wiki/index.php/Main_Page[Fail2ban]. Fail2ban is designed to protect servers from brute force attacks. It works by scanning log files (such as those for _ssh_, _web_, _mail_, and _log_ servers) for certain patterns, specific to each server, and taking actions should those patterns be found.

Actions include banning the IP from which the detected actions originate. This makes the process more difficult and prevents DDOS-style attacks. However, after a predefined time period, the banned IP is usually unbanned again.

This helps if the login attempts were genuine, so that users don’t lock themselves out permanently. An example of such an action is users attempting to brute force log in to a server via ssh. In this case, Fail2ban would look for something similar to the following in `/var/log/auth.log`:

----
Mar 15 11:17:37 yourhost sshd[10912]: input_userauth_request: invalid user audra [preauth]
Mar 15 11:17:37 yourhost sshd[10912]: pam_unix(sshd:auth): check pass; user unknown
Mar 15 11:14:51 yourhost sshd[10835]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=221.194.44.231  user=root
Mar 15 11:14:57 yourhost sshd[10837]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=221.194.44.231  user=root
Mar 15 11:14:59 yourhost sshd[10837]: Failed password for root from 221.194.44.231 port 46838 ssh2
Mar 15 11:15:04 yourhost sshd[10837]: message repeated 2 times: [ Failed password for root from 221.194.44.231 port 46838 ssh2]
Mar 15 11:15:04 yourhost sshd[10837]: Received disconnect from 221.194.44.231: 11:  [preauth]
----

NOTE: If you’re not familiar with what’s going on, this snippet highlights a number of failed login attempts.

=== Using Fail2ban to Secure an ownCloud Login

On Ubuntu, you can install Fail2ban using the following commands:

[source,bash]
----
apt update && apt upgrade
apt install fail2ban
----

Fail2ban installs several default filters for _Apache_ and various other services, but none for ownCloud. Given that, we have to define our own filter. To do so, you first need to make sure that ownCloud uses your local timezone for writing log entries; otherwise, fail2ban cannot react appropriately to attacks. To do this, use the following environment variable:

[source,.env]
----
OWNCLOUD_LOG_TIMEZONE='Europe/Berlin'
----

NOTE: Adjust the timezone to the one that your server is located in, based on  {php-net-url}/manual/en/timezones.php[PHP’s list of supported timezones].

This change takes effect as soon as you save `config.php`. You can test the change by:

. entering false credentials at your ownCloud login screen, then
. checking the timestamp of the resulting entry in ownCloud’s log file.

Next, define a new Fail2ban filter rule for ownCloud. To do so, create a new file called `/etc/fail2ban/filter.d/owncloud.conf`, and insert the
following configuration:

[source,conf]
----
[Definition]
failregex={.*Login failed: \'.*\' \(Remote IP: \'<HOST>\'\)"}
ignoreregex =
----

This filter needs to be loaded when Fail2ban starts, so a further configuration entry is required to be added in `/etc/fail2ban/jail.d/defaults-debian.conf`, which you can see below:

[source,conf]
----
[owncloud]
enabled = true
port = 80,443
protocol = tcp
filter = owncloud
maxretry = 3
bantime = 10800
logpath = /var/owncloud_data/owncloud.log
----

This configuration:

.  Enables the filter rules for TCP requests on ports 80 and 443.
.  Bans IPs for 10800 seconds (3 hours).
.  Sets the path to the log file to analyze for malicious logins

NOTE: The most important part of the configuration is the `logpath` parameter. If this does not point to the correct log file, Fail2ban will either not work properly or refuse to start.

After saving the file, restart Fail2ban by running the following command:

[source,bash]
----
service fail2ban restart
----

To test that the new ownCloud configuration has been loaded, use the following command:

[source,bash]
----
fail2ban-client status
----

If "owncloud" is listed in the console output, the filter is both loaded and active. If you want to test the filter, run the following command, adjusting the path to your `owncloud.log` if necessary:

[source,bash]
----
fail2ban-regex /var/owncloud_data/owncloud.log /etc/fail2ban/filter.d/owncloud.conf
----

The output will look similar to the following if you had one failed login attempt:

[source,bash]
----
fail2ban-regex /var/www/owncloud_data/owncloud.log /etc/fail2ban/filter.d/owncloud.conf

Running tests
=============

Use   failregex file : /etc/fail2ban/filter.d/owncloud.conf
Use         log file : /var/www/owncloud_data/owncloud.log

Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] {.*Login failed: \'.*\' \(Remote IP: \'<HOST>\'\)"}
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [40252] ISO 8601
`-

Lines: 40252 lines, 0 ignored, 1 matched, 40251 missed
----

The `Failregex` counter increases in increments of 1 for every failed login attempt. To unban an IP locked either during testing or unintentionally, use the following command:

[source,bash]
----
fail2ban-client set owncloud unbanip <IP>
----

You can check the status of your ownCloud filter with the following command:

[source,bash]
----
fail2ban-client status owncloud
----

This will produce an output similar to this:

----
Status for the jail: owncloud
|- filter
|  |- File list:    /var/www/owncloud_data/owncloud.log
|  |- Currently failed: 1
|  `- Total failed: 7
`- action
   |- Currently banned: 0
   |  `- IP list:
   `- Total banned: 1
----
