[IMPORTANT]
====
When upgrading, also check the minimum and maximum supported PHP version of the ownCloud target release. An ownCloud release may require a particular minimum and/or maximum PHP version. Check that the PHP version provided by the Operating System meets the requirements. For details see the xref:{latest-docs-version}@docs:ROOT:server_release_notes.adoc[Server Release Notes] and  the xref:{latest-server-version}@server:installation/system_requirements.adoc[System Requirements] for the latest Release.
====

[TIP]
====
If required, you can skip major releases when upgrading your ownCloud installation. However, we recommend that you first upgrade to the latest point release of your respective minor version, e.g., _10.9.1_.
See xref:maintenance/package_upgrade.adoc#upgrading-across-skipped-releases[Upgrading Across Skipped Releases] for more information.

If you are on ownCloud 8.2.11, 9.0.9, 9.1.X, or 10.X.Y you can go directly to the latest server version.

Here are some examples:

[cols=">10%,^25%,65%",options="header",stripes=even]
|===
|Version
|Can Upgrade to {latest-server-download-version} ?
|Requirements

|10.X.Y
|Yes
|

|9.1.8
|Yes
|

|9.1.0
|Yes
|

|9.0.9
|Yes
|

|9.0.8
|*No*
|Must upgrade to 9.0.9 first.

|8.2.11
|Yes
|

|8.2.10
|*No*
|Must upgrade to 8.2.11 first.

|7.0.15
|*No*
|Must upgrade to 8.0.16, then to 8.1.12, and then to 8.2.11 first.

|7.0.10
|*No*
|Must upgrade to 7.0.15, then to 8.0.16, then to 8.1.12, and then to 8.2.11 first.
|===
====
