= Custom Groups

Marketplace URL: {oc-marketplace-url}/apps/customgroups[Custom Groups]

Use these commands to configure the Custom Groups app.

Parameterization should be done with the `occ config` command set, though some but not all settings result in an entry in config.php which also can be set manually.

// note that the behaviour of the config:app settings was derived from the code of the app, see https://github.com/owncloud/customgroups and an issue https://github.com/owncloud/docs-webui/pull/41

== Get a Current Setting

You can get the value of a current setting. For details how to do so see the xref:config-commands[Config Command Set].
  
== Disallow Admin Access

By default, administrators can administrate custom groups of an instance. When changed, only group admins can administrate custom groups. You can change this behaviour with the following command:

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:system:set \
  customgroups.disallow-admin-access-all \
  --type boolean --value true
----

This occ command will create a key-value pair in your config.php which must be writable for the webserver user. You can also do this manually by adding the following key in config.php:

[source.plaintext]
----
  'customgroups.disallow-admin-access-all' => true,
----

== Disallow Members of Defined Groups

You can hide custom groups from a user's personal settings page based on a user's group membership. This makes it easier to collect users you want to exclude into defined groups which will be further used for this setting:

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:system:set \
  customgroups.disallowed-groups \
  --type json \
  --value '["no_guest_app_users", "project5"]'
----

This occ command will create a key-value pair in your config.php which must be writable for the webserver user to be set. You can also set this manually by adding the following key in config.php:

[source.plaintext]
----
  'customgroups.disallowed-groups' => 
  array (
    0 => 'no_guest_app_users',
    1 => 'project5',
  ),
----

== Restrict Group Creation

This setting defines if ordinary users are allowed to create custom groups. By default, all users can create custom groups, but this can be restricted to admins (if allowed as above) and group-admins. Values to be set can be 'true' and 'false', defaults to 'false'.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
  customgroups \
  only_subadmin_can_create \
  --value 'true'
----

== Restrict Add or Remove Group Members

This setting defines if an existing ordinary group member is allowed to add other users to the target group or remove them. By default, all users can add members to groups, but this can be restricted to admins (if allowed as above) and group-admins. Values to be set can be 'yes' and 'no', defaults to 'no'.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
  core \
  shareapi_only_share_with_group_members \
  --value 'yes'
----

== Allow Duplicate Group Display Names

This setting allows the creation of multiple groups with the same display name. By default, group display names must be unique, but it can be be allowed to have multiple identical group display names. Values to be set can be 'true' and 'false', defaults to 'false'.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
  customgroups \
  allow_duplicate_names \
  --value 'false'
----
