= Full Text Search 

Use these commands when you manage full text search related tasks.

== Command Description

[source,plaintext]
----
search
  search:index:create    Create initial Search Index for one or all users. 
                         This command could not update the search index correctly 
                         after the initial indexing.
  search:index:rebuild   Rebuild the search index for a given User. 
                         If you want to rebuild the whole index, run
                         `search:index:reset` and then `search:index:create --all`
  search:index:reset     Reset the index
  search:index:update    Update the search index by running all pending background jobs.
----

In addition to the settings provided by the Full Text Search app, you can set/read additional options via the `occ config:app` commands. These are xref:set-app-modes[Set App Modes], xref:index-metadata-only[Index Metadata Only] and xref:limit-metadata-search-for-groups[Limit Metadata Search for Groups]

== Create the Full Text Search Index

The command `search:index:create` creates the initial full text search index for one or all users. 

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:create <user_id> (<user_id>)...
----

=== Arguments

[width="100%",cols="20%,100%"]
|===
| `<user_id>` 
| The id of the user (or space-separated list of user ids) to create a full text search index for.
A full text search index is created for all users, if this value is omitted.
|===

=== Options

[width="100%",cols="20%,100%"]
|===
| `--all` 
| Will create index for all files of all known users.
|===

=== Example 1

This example creates a full text search index for the user with user id `testuser`.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:create testuser

Indexing user testuser
----

=== Example 2

This example creates a full text search index for the users with user ids `admin` and `testuser`.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:create admin testuser

Indexing user admin
Indexing user testuser
----

== Rebuild the Full Text Search Index

Rebuild the search index for a given User. +
If you want to rebuild the whole index, run `search:index:reset` and then `search:index:create --all`

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:rebuild <user_id> (<user_id>)...
----

=== Arguments

[width="100%",cols="20%,100%"]
|===
| `<user_id>` 
| Provide a userId. This argument is required.
|===

=== Options

[width="100%",cols="20%,100%"]
|===
| `-q` `--quiet` 
| Do not output any message.
| `-f` `--force` 
| Use this option to reset the index without further questions.
|===

=== Example 1

This example rebuilds the full text search index for the user with user id `testuser`.

.Rebuild the index for a single user
[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:rebuild testuser

Indexing user testuser

This will delete all full text search index data for testuser! Do you want to proceed?
  [0] no
  [1] yes
 > 1
Rebuilding full text search Index for testuser
----

=== Example 2

This example rebuilds the full text search index for the users with user ids `admin` and `testuser`.

.Rebuild the index for multiple users
[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:rebuild admin testuser

This will delete all search index data for admin, testuser! Do you want to proceed?
  [0] no
  [1] yes
 > 1
Rebuilding Search Index for admin
Rebuilding Search Index for testuser
----

=== Rebuild the Entire Index

The entire index can be rebuilt by running the following two commands:

[source="console",subs="attributes+"]
----
{occ-command-example-prefix} search:index:reset
{occ-command-example-prefix} search:index:create --all
----

== Reset the Full Text Search Index

The command `search:index:reset` resets (recreates and clears) the full text search index for all users.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:reset
----

=== Arguments

[width="100%",cols="20%,100%"]
|===
| `-f` `--force` 
| Use this option to reset the index without further questions.
|===

=== Example

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:reset
This will delete the whole search index! Do you want to proceed?
  [0] no
  [1] yes
 > 1
Search index has been reset.
----

== Update the Full Text Search Index

Updates to the search index due to changed content or changed metadata are happening via background jobs that are added to a queue. These background jobs are normally run by the ownCloud cronjob. The command `search:index:update` updates the full text search index by running all pending background jobs.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:update
----

=== Arguments

[width="100%",cols="20%,100%"]
|===
| `-q` `--quiet` 
| Suppress all output from the command.
|===

=== Example

This example updates the full text search index for all users.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} search:index:update
Start Updating the Elastic search index:
No pending jobs found.
----

== Set App Modes

To do an initial full indexing without the Full Text Search app interfering, it can be put in passive mode. See the xref:configuration/general_topics/search.html#app-modes[App Modes] section in the Full Text Search description for details.

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
    search_elastic mode --value passive
----

Switching back to active mode can be done by running the following command:

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
    search_elastic mode --value active
----

== Restrict Search Results

Search results can be restricted in different ways, see the xref:configuration/general_topics/search.adoc#restrict-search-results[Restrict Search Results] section in the Full Text Search description for details.

=== Index Metadata Only

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
    search_elastic nocontent --value true
----

Switching back to provide all content can be done by running the following command:

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
    search_elastic nocontent --value false
----

=== Limit Metadata Search for Groups 

[source,bash,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
    search_elastic group.nocontent \
    --value group1,group2,"group with blank"
----
