= User Two-Factor Authentication
:toc: right

== Introduction

With two-factor authentication (2FA), users can access their ownCloud web accounts only by using a trusted device like their mobile phone. When users want to sign in, they need to provide two pieces of information (factors):

* the password,
* the six-digit verification code that's automatically displayed on the trusted device or sent to the phone number.

== Setting Up 2FA

To provide 2FA functionality, an app like the {oc-marketplace-url}/apps/twofactor_totp[2-Factor Authentication] needs to be installed and enabled.

If a two-factor provider app is enabled, it is enabled for all users by default *but* _a user has to opt in_, though the provider can decide whether or not the user has to pass the challenge.

TIP: For the opt-in function to work, ImageMagick and php-imagick are required to create the QR code. Depending on your operating system, these packages may need to be installed manually.

== Using 2FA with ownCloud Desktop and Mobile Apps

ownCloud Desktop and Mobile Apps support 2FA login with browser-based login flows.

=== Enable OAuth 2.0 App (recommended)

ownCloud Desktop client will open the login page in the system web browser, and ownCloud Mobile Apps will open the login page in an embedded web view. After entering the regular credentials, users will see a second page, where they need to enter the second factor.

Here you can find more information:

- https://doc.owncloud.com/server/next/admin_manual/configuration/user/user_oauth2.html

=== App Passwords / Tokens

Without the OAuth 2.0 App, users need to log in to their ownCloud account in a regular web browser first, then create an app password or tokens, which can be used in the ownCloud Desktop and Mobile apps.

Here you can find more information:

- https://doc.owncloud.com/webui/next/classic_ui/personal_settings/security.html#app-passwords-tokens

== Troubleshooting

=== Tasks for the User

Because the user has to opt in, see the xref:{latest-webui-version}@webui:classic_ui:personal_settings/security.adoc[Security section in Personal Settings] for tasks on the user side.

=== Second Factor is Inaccessible

In case a user loses access to the second factor, e.g. by breaking or losing the phone with two-factor SMS/app verification, the user is locked out. To give the user access to the account again, an admin can temporarily disable the two-factor check _for that user_ via the
xref:configuration/server/occ_command.adoc#two-factor-authentication[occ commands for Two-Factor Authentication]. 
After the issue has been fixed, the admin can reenable two-factor authentication for that user.

=== Manage Secrets

If owncloud's {oc-marketplace-url}/apps/twofactor_totp[2-Factor Authentication] is used, the admin can manage
the secrets via xref:configuration/server/occ_command.adoc#two-factor-totp[occ Two-Factor TOTP commands].
