= User Authentication with IMAP, SMB, and FTP
:toc: right
:toclevels: 1

== Introduction

NOTE: The described configurations are examples, see the xref:installation/configuration_notes.adoc[Configuration Notes] documentation for more options.

You may configure additional user backends in ownCloud’s configuration file (`config/config.php`) using the following syntax:

[source,php]
----
<?php

"user_backends" => [
    0 => [
        "class"     => ...,
        "arguments" => [
            0 => ...
        ],
    ],
],
----

Currently the https://github.com/owncloud/user_external[External user support app] (user_external), _which is not enabled by default_, provides three backends. These are:

* xref:imap[IMAP]
* xref:smb[SMB]
* xref:ftp[FTP]

See xref:installation/apps_management_installation.adoc[Installing and Managing Apps] for more information.

== IMAP

Provides authentication against IMAP servers.

[cols=",",options="header",]
|====
| Option
| Value/Description

| Class
| `OC_User_IMAP`.

| Arguments
| A mailbox string as defined +
{php-net-url}/manual/en/function.imap-open.php[in the PHP documentation].

| Dependency
| The PHP IMAP extension is not part of the image. If you want to authenticate against IMAP, you need to build your own image based on the official ownCloud image and add the extension to it.
|====

=== Example

[source,php]
----
<?php

"user_backends" => [
    0 => [
        "class"     => "OC_User_IMAP",
        "arguments" => [
            // The IMAP server to authenticate against
            '{imap.gmail.com:993/imap/ssl}',
            // The domain to send email from
            'example.com'
        ],
    ],
],
----

IMPORTANT: The second `arguments` parameter ensures that only users from that domain are allowed to login. When set, after a successful login, the domain will be stripped from the email address and the rest used as an ownCloud username. For example, if the email address is `guest.user@example.com`, then `guest.user` will be the username used by ownCloud.

SMB
---

Provides authentication against Samba servers.

[cols=",",options="header",]
|====
| Option
| Value/Description

| Class
| `OC_User_SMB`

| Arguments
| The samba server to authenticate against.

| Dependency
| xref:configuration/files/external_storage/smb.adoc[smbclient].
|====

=== Example

[source,php]
----
<?php

"user_backends" => [
    [
        "class"     => "OC_User_SMB",
        "arguments" => [
            'localhost'
        ],
    ],
],
----

FTP
---

Provides authentication against FTP servers.

[cols=",",options="header",]
|===
| Option
| Value/Description

| Class
| `OC_User_FTP`

| Arguments
| The FTP server to authenticate against.

|===

=== Example

[source,php]
----
<?php

"user_backends" => [
    [
        "class"     => "OC_User_FTP",
        "arguments" => [
            'localhost'
        ],
    ],
],
----
