= Install ownCloud on Ubuntu 20.04
:toc: right

== Introduction

This is a short guide to installing ownCloud on a fresh installation of Ubuntu 20.04. Run the following commands in your terminal to complete the installation.

This guide can not go into details and has its limits by nature. If you experience issues like with dependencies of PHP or other relevant things like the operating system, web server or database, look at the xref:installation/manual_installation/manual_installation.adoc#ubuntu-20-04-lts-server[Detailed Installation Guide] for more information.

== Prerequisites and Notes

* A fresh installation of https://www.ubuntu.com/download/server[Ubuntu 20.04] with SSH enabled.
* This guide assumes that you are working as the root user.
* Your ownCloud directory will be located in `/var/www/owncloud/`.
* php 7.4 is the default version installable with Ubuntu 20.04.
* Use the correct xref:installation/manual_installation/manual_installation_apache.adoc#multi-processing-module-mpm[Multi-Processing Module (MPM)].

== Preparation

First, ensure that all the installed packages are entirely up to date, and that PHP is available in the APT repository.
To do so, follow the instructions below:

[source,bash]
----
apt update && \
  apt upgrade -y
----

=== Create the occ Helper Script

Create a helper script to simplify running xref:configuration/server/occ_command.adoc[occ commands]:

[source,bash]
----
FILE="/usr/local/bin/occ"
cat <<EOM >$FILE
#! /bin/bash
cd /var/www/owncloud
sudo -E -u www-data /usr/bin/php /var/www/owncloud/occ "\$@"
EOM
----

Make the helper script executable:

[source,bash]
----
chmod +x $FILE
----

=== Install the Required Packages

[source,bash]
----
apt install -y \
  apache2 \
  libapache2-mod-php \
  mariadb-server \
  openssl redis-server wget \
  php-imagick php-common php-curl \
  php-gd php-imap php-intl \
  php-json php-mbstring php-mysql \
  php-ssh2 php-xml php-zip \
  php-apcu php-redis php-ldap \
  php-opcache
----

=== Install smbclient php module

First install the required packages:

[source,bash]
----
apt-get install -y libsmbclient-dev php-dev php-pear
----

Install smblclient php module using pecl

[source,bash]
----
pecl install smbclient-stable
echo "extension=smbclient.so" > /etc/php/7.4/mods-available/smbclient.ini
phpenmod smbclient
systemctl restart apache2
----

Check if it was successfully activated 

[source,bash]
----
php -m | grep smbclient
----
This should show the following output

[source,bash]
----
libsmbclient
smbclient
----

=== Install the Recommended Packages

Additional useful tools helpful for debugging:

[source,bash]
----
apt install -y \
  unzip bzip2 rsync curl jq \
  inetutils-ping  ldap-utils\
  smbclient
----

=== Configure Apache

==== Create a Virtual Host Configuration

[source,apache]
----
FILE="/etc/apache2/sites-available/owncloud.conf"
cat <<EOM >$FILE
<VirtualHost *:80>
# ServerName <add a valid ServerName> and uncommment
DirectoryIndex index.php index.html
DocumentRoot /var/www/owncloud
<Directory /var/www/owncloud>
  Options +FollowSymlinks -Indexes
  AllowOverride All
  Require all granted

 <IfModule mod_dav.c>
  Dav off
 </IfModule>

 SetEnv HOME /var/www/owncloud
 SetEnv HTTP_HOME /var/www/owncloud
</Directory>
</VirtualHost>
EOM
----

==== Enable the Virtual Host Configuration

[source,bash]
----
a2dissite 000-default
a2ensite owncloud.conf
systemctl reload apache2
----

=== Configure the Database

[source,bash]
----
systemctl start mariadb
mysql -u root -e "CREATE DATABASE IF NOT EXISTS owncloud; \
GRANT ALL PRIVILEGES ON owncloud.* \
  TO owncloud@localhost \
  IDENTIFIED BY 'password'";
----

==== Enable the Recommended Apache Modules

[source,bash]
----
echo "Enabling Apache Modules"
a2enmod dir env headers mime rewrite setenvif
service apache2 reload
----

== Installation

=== Download ownCloud

[source,bash,subs="attributes+"]
----
cd /var/www/
wget https://download.owncloud.org/community/{oc-complete-name}.tar.bz2 && \
tar -xjf {oc-complete-name}.tar.bz2 && \
chown -R www-data. owncloud
----

=== Install ownCloud

[source,bash]
----
occ maintenance:install \
    --database "mysql" \
    --database-name "owncloud" \
    --database-user "owncloud" \
    --database-pass "password" \
    --data-dir "/var/www/owncloud/data" \
    --admin-user "admin" \
    --admin-pass "admin"
----

=== Configure ownCloud's Trusted Domains

[source,bash]
----
myip=$(hostname -I|cut -f1 -d ' ')
occ config:system:set trusted_domains 1 --value="$myip"
----

=== Set Up a Cron Job

Set your background job mode to cron:

[source,bash]
----
occ background:cron
----

Configure the execution of the cron job to every 15 min:

[source,bash]
----
echo "*/15  *  *  *  * /var/www/owncloud/occ system:cron" \
  | sudo -u www-data -g crontab tee -a /var/spool/cron/crontabs/www-data
----

[NOTE]
====
If you need to sync your users from an LDAP or Active Directory Server, add this additional xref:configuration/server/background_jobs_configuration.adoc[Cron job]. Every 15 minutes this cron job will sync LDAP users in ownCloud and disable the ones who are not available for ownCloud. Additionally, you get a log file in `/var/log/ldap-sync/user-sync.log` for debugging.
====

[source,bash]
----
echo "*/15 * * * * /var/www/owncloud/occ user:sync 'OCA\User_LDAP\User_Proxy' -m disable -vvv >> /var/log/ldap-sync/user-sync.log 2>&1" \
  | sudo -u www-data -g crontab tee -a /var/spool/cron/crontabs/www-data
mkdir -p /var/log/ldap-sync
touch /var/log/ldap-sync/user-sync.log
chown www-data. /var/log/ldap-sync/user-sync.log
----

=== Configure Caching and File Locking

[source,bash,subs="attributes+"]
----
occ config:system:set \
   memcache.local \
   --value '\OC\Memcache\APCu'
occ config:system:set \
   memcache.locking \
   --value '\OC\Memcache\Redis'
occ config:system:set \
   redis \
   --value '{"host": "{oc-examples-server-ip}", "port": "{std-port-redis}"}' \
   --type json
----

=== Configure Log Rotation

[source,bash]
----
FILE="/etc/logrotate.d/owncloud"
sudo cat <<EOM >$FILE
/var/www/owncloud/data/owncloud.log {
  size 10M
  rotate 12
  copytruncate
  missingok
  compress
  compresscmd /bin/gzip
}
EOM
----

==== Finalize the Installation

Make sure the permissions are correct:

[source,bash]
----
cd /var/www/
chown -R www-data. owncloud
----

**ownCloud is now installed. You can confirm that it is ready to use by pointing your web browser to your ownCloud installation.**

To check if you have installed the correct vesion of ownCloud and that the occ command is working, execute the following:

[source,bash]
----
occ -V
----

IMPORTANT: We recommend you check out the section xref:configuration/server/harden_server.adoc[Hardening and Security Guidance] next.
